### PR TITLE
Add in current PDP10 simulator and improved panel code.

### PR DESCRIPTION
**Pull request by rcornwell**

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
We need to test every function thoroughly before updating the emulator.  Here are some known issues:

- ~~READ IN doesn't work in RUN state.  I'm not sure if it should, but Oscar and I had it do so.  We'll have to check the docs.~~
  READ IN should not do anything during RUN state.
- Pushing some momentary switches results in emulator output to the console teletype which looks bad and interferes with output from PDP-10 programs.

**Comment by larsbrinkhoff** [comment]
- ~~Memory indicators would normally display the ITS job.  Now it's stuck on MEMORY DATA.~~
  Fixed, see below.

**Comment by larsbrinkhoff** [comment]
- ~~Data switch 0 doesn't make ITS go to NTS DDT.~~
Fixed.

**Comment by rcornwell** [comment]
If RUN is on Readin has no effect.  DATAI APR will read the switch register. DATAO PI will write the memory indicator.

I am not sure what I can do to remove the messages on the console, since these are caused by interjections of commands into SCP. The Halt is the standard message that prints when the CPU is halted.

**Comment by rcornwell** [comment]
The ITS issues should be fixed. It still prints things when Keys are pressed.

**Comment by larsbrinkhoff** [comment]
~~When ITS is running, the PROGRAM DATA indicator is now on (as expected), but the MI lights don't show the expected DATAO PI pattern.~~

~~Looks like the old "Panama" emulator also doesn't show (what I expect) on the MI, so I'll have to look into this.~~

I was just looking at the wrong row!  It works fine.

**Comment by rcornwell** [comment]
Not sure why it is not.

**Comment by larsbrinkhoff** [comment]
Tried dropping the GO at the end of boot.ini.  The computer powers up and enters a stopped state, which is good.

Then START from address 1000 to enter the blink loop.  That's fine.

However, pushing SING INST to single step with CONT.... seems not entirely ok.

Pushing START with SING INST down doesn't stop at or after the first instruction.

EXAMINE THIS/NEXT are ok.

**Comment by rcornwell** [comment]
Will fix this... this was working before.

**Comment by rcornwell** [comment]
Fixed

**Pull request merged**
